body_forge/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls')),
    path('accounts/', include('accounts.urls')),
    path('workout/', include('workouts.urls')),
    path('forum/', include('forum.urls')),
]

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forum/urls.py
from django.urls import path, include

from forum.views import CreateQuestion, ListQuestionsView, approve_question, DetailsQuestionView, delete_question, \
    AnswerCreateView

urlpatterns = [
    path('', include([
        path('', ListQuestionsView.as_view(), name='qu-list'),
        path('add-question/', CreateQuestion.as_view(), name='qu-create'),
        path('question/<int:question_pk>/add-answer/', AnswerCreateView.as_view(), name='an-create'),
        path('details-qu/<int:pk>/', DetailsQuestionView.as_view(), name='qu-details'),
        path('approve-qu/<int:pk>/', approve_question, name='qu-approve'),
        path('delete-qu/<int:pk>/', delete_question, name='qu-delete'),
    ])),
]

workouts/urls.py
from django.urls import path, include

from workouts.views import (
    CreateWorkoutView, CreateWorkoutTypeView, DeleteWorkoutTypeView, CreateExerciseView,
    CreateMuscleGroupView, DeleteMuscleGroupView, DeleteExerciseView, CreateSetView, WorkoutViewSet,
    WorkoutProgressAPIView, DetailsWorkoutView,
)

urlpatterns = [

    path('api/', include([
        path('all-workouts/', WorkoutViewSet.as_view(), name='api-workouts'),
        path('progress/', WorkoutProgressAPIView.as_view(), name='api-workout-progress'),
    ])),

    path('', CreateWorkoutView.as_view(), name='wt-create'),
    path('add-type/', CreateWorkoutTypeView.as_view(), name='wt-type-create'),
    path('delete-type/<int:pk>/', DeleteWorkoutTypeView.as_view(), name='wt-type-delete'),
    path('delete-muscle-group/<int:pk>/', DeleteMuscleGroupView.as_view(), name='mg-delete'),
    path('delete-exercise/<int:pk>/', DeleteExerciseView.as_view(), name='ex-delete'),

    path('<int:workout_pk>/', include([
        path('details/', DetailsWorkoutView.as_view(), name='wt-details'),

        path('add-exercise/', CreateExerciseView.as_view(), name='ex-create'),
        path('add-muscle-group/', CreateMuscleGroupView.as_view(), name='mg-create'),
        path('exercise/<int:exercise_pk>/', include([
            path('add-set/', CreateSetView.as_view(), name='set-create'),
        ])),
    ])),
]

workouts/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django_extensions.db.models import TimeStampedModel

UserModel = get_user_model()


class MuscleGroup(models.Model):
    user = models.ForeignKey(
        to=UserModel,
        on_delete=models.CASCADE,
        related_name='muscle_groups'
    )
    name = models.CharField(
        max_length=100,
    )

    class Meta:
        unique_together = ('user', 'name')

    def __str__(self):
        return self.name


class WorkoutType(models.Model):
    user = models.ForeignKey(
        to=UserModel,
        on_delete=models.CASCADE,
        related_name='workout_types'
    )
    name = models.CharField(
        max_length=100,
    )
    muscle_group = models.ManyToManyField(
        'MuscleGroup',
        related_name='workout_types',
        blank=True,
    )

    class Meta:
        unique_together = ('user', 'name')

    def __str__(self):
        return self.name


class Exercise(TimeStampedModel):
    user = models.ForeignKey(
        to=UserModel,
        on_delete=models.CASCADE,
        related_name='exercises'
    )
    name = models.CharField(
        max_length=100
    )
    muscle_group = models.ForeignKey(
        'MuscleGroup',
        on_delete=models.CASCADE,
        related_name='exercises',
    )
    workout = models.ForeignKey(
        'Workout',
        on_delete=models.CASCADE,
        related_name='exercises'
    )

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return f"{self.name} ({self.muscle_group.name})"


class Workout(TimeStampedModel):
    user = models.ForeignKey(
        to=UserModel,
        on_delete=models.CASCADE,
        related_name="workouts"
    )
    workout_type = models.ForeignKey(
        'WorkoutType',
        on_delete=models.SET_NULL,
        null=True,
        related_name="workouts",
    )

    def __str__(self):
        return f"Workout on {self.created.strftime('%Y-%m-%d %H:%M')} by {self.user.profile.username}"


class ExerciseSet(TimeStampedModel):
    exercise = models.ForeignKey(
        'Exercise',
        on_delete=models.CASCADE,
        related_name='sets',
    )
    repetitions = models.PositiveIntegerField()
    weight = models.DecimalField(
        max_digits=5,
        decimal_places=2,
    )

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return f"{self.repetitions} reps @ {self.weight:.2f} kg"

workouts/forms.py
from django import forms
from django.core.exceptions import ValidationError

from workouts.models import Workout, WorkoutType, Exercise, MuscleGroup, ExerciseSet


class CreateWorkoutForm(forms.ModelForm):
    class Meta:
        model = Workout
        fields = ['workout_type']

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

        if user:
            self.fields['workout_type'].queryset = WorkoutType.objects.filter(user=user)


class CreateWorkoutTypeForm(forms.ModelForm):
    class Meta:
        model = WorkoutType
        fields = ['name']

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

    def clean_name(self):
        name = self.cleaned_data.get('name')
        if WorkoutType.objects.filter(user=self.user, name__iexact=name).exists():
            raise forms.ValidationError("You already have a workout type with this name.")
        return name


class CreateExerciseForm(forms.ModelForm):
    class Meta:
        model = Exercise
        fields = ['name', 'muscle_group']

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        if self.user:
            self.fields['muscle_group'].queryset = MuscleGroup.objects.filter(user=self.user)


class CreateMuscleGroupForm(forms.ModelForm):
    class Meta:
        model = MuscleGroup
        fields = ['name']
        widgets = {
            'name': forms.TextInput(attrs={
                'required': True,
                'maxlength': 100,
                'placeholder': 'Enter muscle group name...'
            })
        }

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

    def clean_name(self):
        name = self.cleaned_data.get('name')
        if MuscleGroup.objects.filter(user=self.user, name__iexact=name).exists():
            raise forms.ValidationError("You already have a muscle group with this name.")
        return name


class CreateSetForm(forms.ModelForm):
    class Meta:
        model = ExerciseSet
        fields = ['repetitions', 'weight']
        widgets = {
            'repetitions': forms.NumberInput(attrs={'min': 1}),
            'weight': forms.NumberInput(attrs={'min': 0, 'step': '0.01'}),
        }

    def __init__(self, *args, user=None, **kwargs):
        super().__init__(*args, **kwargs)
        self.user = user  #

workouts/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Sum, F
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView

from common.mixins import UserObjectOwnerMixin
from workouts.forms import (CreateWorkoutForm, CreateWorkoutTypeForm, CreateExerciseForm, CreateMuscleGroupForm,
                            CreateSetForm, )
from workouts.models import Workout, WorkoutType, Exercise, MuscleGroup, ExerciseSet
from workouts.serializers import WorkoutSerializer


class CreateWorkoutView(LoginRequiredMixin, UserObjectOwnerMixin, CreateView):
    model = Workout
    form_class = CreateWorkoutForm
    template_name = 'workouts/wt-create.html'

    def get_success_url(self):
        return reverse_lazy('wt-details', kwargs={'workout_pk': self.object.pk})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['wt_types'] = WorkoutType.objects.filter(user=self.request.user)
        return context


class DetailsWorkoutView(LoginRequiredMixin, DetailView):
    model = Workout
    template_name = 'workouts/wt-details.html'
    context_object_name = 'workout'
    pk_url_kwarg = 'workout_pk'

    def get_queryset(self):
        return Workout.objects.filter(user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        workout = self.get_object()
        context['workout'] = workout
        context['exercises'] = self.object.exercises.all().prefetch_related('sets')
        return context


class StartWorkoutView(LoginRequiredMixin, DetailView):
    model = Workout
    template_name = 'workouts/wt-create.html'
    context_object_name = 'workout'
    pk_url_kwarg = 'workout_pk'

    def get_queryset(self):
        return Workout.objects.filter(user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        workout = self.get_object()
        context['workout'] = workout
        context['exercises'] = self.object.exercises.all().prefetch_related('sets')


class WorkoutViewSet(APIView):
    def get(self, request):
        workouts = Workout.objects.all()
        serializer = WorkoutSerializer(workouts, many=True)
        return Response({'workouts': serializer.data})


class WorkoutProgressAPIView(APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request, *args, **kwargs):
        user = request.user

        total_workouts = Workout.objects.filter(user=user).count()
        total_volume_lifted = ExerciseSet.objects.filter(
            exercise__workout__user=user
        ).aggregate(total_volume=Sum(F('repetitions') * F('weight')))

        data = {
            'total_workouts_completed': total_workouts,
            'total_volume_lifted': total_volume_lifted['total_volume'] or 0,
        }
        return Response(data)


class CreateWorkoutTypeView(LoginRequiredMixin, UserObjectOwnerMixin, CreateView):
    model = WorkoutType
    form_class = CreateWorkoutTypeForm
    template_name = 'workouts/wt-type-create.html'

    def get_success_url(self):
        return reverse('wt-create')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


class DeleteWorkoutTypeView(LoginRequiredMixin, DeleteView):
    model = WorkoutType

    def post(self, request, *args, **kwargs):
        workout_type = self.get_object()

        if workout_type.user == request.user:
            workout_type.delete()
            return JsonResponse({'success': True})
        return JsonResponse({'success': False}, status=403)


class CreateExerciseView(LoginRequiredMixin, CreateView):
    model = Exercise
    form_class = CreateExerciseForm
    template_name = 'workouts/ex-create.html'

    def dispatch(self, request, *args, **kwargs):
        self.workout = Workout.objects.get(pk=kwargs['workout_pk'], user=request.user)
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.workout = self.workout
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('wt-details', kwargs={'workout_pk': self.workout.pk})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['muscle_groups'] = MuscleGroup.objects.filter(user=self.request.user)
        context['workout'] = self.workout
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


class CreateMuscleGroupView(LoginRequiredMixin, UserObjectOwnerMixin, CreateView):
    model = MuscleGroup
    form_class = CreateMuscleGroupForm
    template_name = 'workouts/mg-create.html'

    def dispatch(self, request, *args, **kwargs):
        self.workout_pk = kwargs.get('workout_pk')
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse_lazy('ex-create', kwargs={'workout_pk': self.workout_pk})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['workout_pk'] = self.workout_pk
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


class DeleteMuscleGroupView(LoginRequiredMixin, DeleteView):
    model = MuscleGroup

    def post(self, request, *args, **kwargs):
        muscle_group = self.get_object()

        if muscle_group.user == request.user:
            muscle_group.delete()
            return JsonResponse({'success': True})
        return JsonResponse({'success': False, 'error': 'Unauthorized'}, status=403)


class DeleteExerciseView(LoginRequiredMixin, DeleteView):
    model = Exercise

    def post(self, request, *args, **kwargs):
        exercise = self.get_object()

        if exercise.user == request.user:
            exercise.delete()
            return JsonResponse({'success': True})
        return JsonResponse({'success': False, 'error': 'Unauthorized'}, status=403)


class CreateSetView(LoginRequiredMixin, CreateView):
    model = ExerciseSet
    form_class = CreateSetForm
    template_name = 'workouts/set-create.html'

    def form_valid(self, form):
        form.instance.exercise = self.exercise
        return super().form_valid(form)

    def dispatch(self, request, *args, **kwargs):
        self.workout = get_object_or_404(Workout, pk=kwargs['workout_pk'], user=request.user)
        self.exercise = get_object_or_404(Exercise, pk=kwargs['exercise_pk'], user=request.user, workout=self.workout)
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['workout'] = self.workout
        context['exercise'] = self.exercise
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_success_url(self):
        return reverse_lazy('wt-details', kwargs={'workout_pk': self.workout.pk})

templates/workouts/ex-create.html
{% extends 'base.html' %}
{% load placeholder_filter %}
{% load static %}

{% block content %}
    <div class="background-img d-flex-col-cent">
        <div class="container blur-background">
            <form class="wt-type-form d-flex-col-cent gap25" method="post">
                {% csrf_token %}

                <div class="input-field">
                    <h4 class="label">Exercise Name:</h4>
                    {{ form.name|placeholder:"e.g., Bench Press, Squats" }}
                    <div class="error-field fade-effect">
                        {{ form.non_field_errors }}
                        {{ form.name.errors }}
                    </div>
                </div>

                {% if muscle_groups %}
                    <label for="muscleGroupsList" class="second-title">Select a Muscle Group:</label>

                    <select name="muscle_group" id="muscleGroupsList">
                        {% for mg in muscle_groups %}
                            <option value="{{ mg.id }}">{{ mg.name }}</option>
                        {% endfor %}
                    </select>

                    <div class="btn-container d-flex gap25">
                        <a href="{% url 'mg-create' workout_pk=workout.pk %}" class="glow-on-hover d-flex-col-cent">Add a New Muscle Group</a>
                        <button type="button" id="deleteMgBtn" class="red-glow-on-hover">
                            Delete Selected Muscle Group
                        </button>
                    </div>

                {% else %}
                    <p>You haven't added any muscle groups yet.</p>
                    <div class="error-field fade-effect">
                        {{ form.muscle_group.errors }}
                    </div>
                    <a href="{% url 'mg-create' workout_pk=workout.pk %}" class="glow-on-hover d-flex-col-cent">Create Muscle Group</a>
                {% endif %}

                <hr class="hr-line">

                <div class="btn-container d-flex gap25">
                    <button type="submit" class="glow-on-hover">Save Exercise</button>
                    <a href="{% url 'wt-details' workout_pk=workout.pk %}" class="red-glow-on-hover d-flex-col-cent">Back to Workout</a>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/workouts/mg-create.html
{% extends 'base.html' %}
{% load placeholder_filter %}
{% load static %}

{% block content %}
    <div class="background-img d-flex-col-cent">
        <div class="container blur-background">
            <form class="wt-type-form d-flex-col-cent" method="post">
                {% csrf_token %}

                <div class="input-field">
                    <h4 class="label">Muscle Group Name:</h4>
                    {{ form.name|placeholder:"e.g., Chest, Back, Legs" }}
                    <div class="error-field fade-effect">
                        {{ form.name.errors }}
                    </div>
                </div>

                <hr class="hr-line">

                <div class="btn-container d-flex gap25">
                    <button type="submit" class="glow-on-hover">Save Muscle Group</button>
                    <a href="{% url 'ex-create' workout_pk=workout_pk %}" class="red-glow-on-hover d-flex-col-cent">Back to Exercise</a>
                </div>

            </form>
        </div>
    </div>
{% endblock %}

templates/workouts/mg-delete-modal.html
<div id="popupModal2" class="modal">
    <div class="modal-content blur-background">
        <h2 class="second-title m-4">Confirm deletion</h2>

        <p>Are you sure you want to delete the muscle group:
            <strong id="mgNamePlaceholder">this</strong>?
        </p>

        <form method="post" class="mg-delete-form" id="deleteMgForm" action="">
            {% csrf_token %}
            <span class="close-btn">&times;</span>
            <button type="submit" class="btn btn-danger">Yes, delete</button>
            <a href="#" class="btn btn-secondary" id="cancelDelete">Cancel</a>
        </form>

    </div>
</div>

templates/workouts/set-create.html
{% extends 'base.html' %}
{% load placeholder_filter %}
{% load static %}

{% block content %}
    <div class="background-img d-flex-col-cent">
        <div class="container blur-background">
            <form class="d-flex-col-cent gap25" method="post">
                {% csrf_token %}

                <div class="input-field">
                    <h4 class="label">Number of Repetitions:</h4>
                    {{ form.repetitions|placeholder:"e.g., 12" }}
                    <div class="error-field fade-effect">
                        {{ form.repetitions.errors }}
                    </div>
                </div>
                <div class="input-field">
                    <h4 class="label">Weight (kg):</h4>
                    {{ form.weight|placeholder:"e.g., 50" }}
                    <div class="error-field fade-effect">
                        {{ form.weight.errors }}
                    </div>
                </div>

                <div class="btn-container d-flex gap25">
                    <button type="submit" class="glow-on-hover">Add Set</button>
                    <a href="javascript:history.back()" class="red-glow-on-hover d-flex-col-cent">Cancel</a>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/workouts/start_workout.html
{% extends "common/base.html" %}

{% block content %}

    <div class="container-2 fade-effect">
        <h1 class="title">Start New Workout</h1>
        <form method="post" class="d-flex-col-cent" action="#">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_workout_type">Workout Type:</label>
                {{ form.workout_type }}
            </div>
            <div class="form-group">
                <label>Muscle Groups:</label>
                {{ form.muscle_groups }}
            </div>
            <button type="submit" class="submit-btn glow-on-hover">Start Workout</button>
        </form>
    </div>

{% endblock %}

templates/workouts/wt-create.html
{% extends 'base.html' %}
{% load placeholder_filter %}
{% load static %}

{% block content %}

    <div class="background-img d-flex-col-cent">
        <div class="container d-flex-col-cent">

            <form method="post" class="wt-create-form d-flex-col-cent blur-background">
                {% csrf_token %}
                <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">

                <section class="wt-type-section d-flex-col-cent gap25">
                    {% if wt_types %}
                        <label class="second-title" for="workoutType">Select a Workout Type:</label>

                        <select name="workout_type" id="workoutType">
                            {% for wt in wt_types %}
                                <option value="{{ wt.id }}">{{ wt.name }}</option>
                            {% endfor %}
                        </select>

                        <div class="btn-container d-flex gap25">
                            <a href="{% url 'wt-type-create' %}" class="glow-on-hover d-flex-col-cent">Add a New Workout Type</a>
                            <button type="button" id="deleteWtBtn" class="red-glow-on-hover danger-btn">
                                Delete Selected Workout Type
                            </button>
                        </div>

                        <hr class="hr-line">

                        <button type="submit" class="glow-on-hover">Start Your Workout</button>

                    {% else %}
                        <p class="second-title">You don't have any workout types yet.</p>
                        <a href="{% url 'wt-type-create' %}" class="glow-on-hover d-flex-col-cent">Create Workout Type</a>
                    {% endif %}

                </section>
            </form>
        </div>
    </div>

{% endblock %}

templates/workouts/wt-details.html
{% extends 'base.html' %}
{% load placeholder_filter %}
{% load static %}

{% block content %}
    <h4 class="wt-info second-title">{{ workout.workout_type }} Workout on {{ workout.created|date:"F d, Y" }}</h4>
    <div class="background-img d-flex-col-cent">
        <div class="content-stack-grow d-flex-col-cent">
            <input type="hidden" id="workoutPkInput" value="{{ workout.pk }}">

            <div class="container blur-background d-flex-col-cent gap15">
                <section class="wt-exercises d-flex-col-cent gap25">
                    {% if exercises %}
                        <label for="exercisesList" class="second-title">Select an Exercise:</label>

                        <select name="exercises" id="exercisesList">
                            {% for ex in exercises %}
                                <option value="{{ ex.id }}">{{ ex.name }}</option>
                            {% endfor %}
                        </select>

                        <button type="button" id="startExerciseBtn" class="glow-on-hover d-flex-col-cent">Start Selected Exercise</button>

                        <div class="btn-container d-flex gap25">
                            <a href="{% url 'ex-create' workout_pk=workout.pk %}" class="glow-on-hover d-flex-col-cent">Add a New Exercise</a>
                            <button type="button" id="deleteExerciseBtn" class="red-glow-on-hover danger-btn">
                                Delete Selected Exercise
                            </button>
                        </div>

                        <hr class="hr-line">

                        <section class="exercise-logs">
                            <h2>Workout Log</h2>
                            {% if exercises %}
                                {% for exercise in exercises %}
                                    <div class="exercise-log">
                                        <h3>{{ exercise.name }} (Muscle Group: {{ exercise.muscle_group.name }})</h3>

                                        {% if exercise.sets.all %}
                                            <ul>
                                                {% for set in exercise.sets.all %}
                                                    <li>Reps: {{ set.repetitions }}, Weight: {{ set.weight }} kg</li>
                                                {% endfor %}
                                            </ul>
                                        {% else %}
                                            <p>No sets have been logged for this exercise yet.</p>
                                        {% endif %}

                                    </div>
                                {% endfor %}
                            {% else %}
                                <p>You haven't logged any exercises for this workout yet.</p>
                            {% endif %}
                        </section>

                        <a href="{% url 'dashboard' pk=user.pk %}" class="glow-on-hover d-flex-col-cent">Finish and Save Workout</a>

                    {% else %}
                        <p class="second-title">You haven't added any exercises to this workout yet.</p>
                        <a href="{% url 'ex-create' workout_pk=workout.pk %}" class="glow-on-hover d-flex-col-cent">Add Your First Exercise</a>
                    {% endif %}
                </section>
            </div>
        </div>
    </div>
{% endblock %}

templates/workouts/wt-start.html
{% extends 'base.html' %}
{% load placeholder_filter %}
{% load static %}

{% block content %}

    <div class="background-img d-flex-col-cent">
        <div class="container d-flex-col-cent">

            <form method="post" class="wt-create-form d-flex-col-cent blur-background">
                {% csrf_token %}
                <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">

                <section class="wt-type-section d-flex-col-cent gap25">
                    {% if wt_types %}
                        <label class="second-title" for="workoutType">Select Workout Type:</label>

                        <select name="workout_type" id="workoutType">
                            {% for wt in wt_types %}
                                <option value="{{ wt.id }}">{{ wt.name }}</option>
                            {% endfor %}
                        </select>

                    {% else %}
                        <p class="second-title">You Dont Have Any Types.</p>
                    {% endif %}

                    <div class="btn-container d-flex gap25">
                        <a href="{% url 'wt-type-create' %}" class="glow-on-hover d-flex-col-cent">Add new workout
                            type</a>
                        <button type="button" id="deleteWorkoutTypeBtn" class="red-glow-on-hover danger-btn">
                            Delete Selected Type
                        </button>
                    </div>
                </section>

                <hr class="hr-line">

                <section class="wt-exercises container d-flex-col-cent gap25">
                    <label for="exercisesList" class="second-title">Select Exercise:</label>

                    {% if exercises %}

                        <select name="exercises" id="exercisesList">
                            {% for ex in exercises %}
                                <option value="{{ ex.id }}">{{ ex.name }}</option>
                            {% endfor %}
                        </select>

                        <button type="button" id="startExerciseBtn" class="glow-on-hover d-flex-col-cent">Start Selected
                            Exercise
                        </button>

                    {% else %}
                        <p class="second-title">You Dont Have Any Exercises.</p>
                    {% endif %}

                    <div class="btn-container d-flex gap25">
                        <a href="{% url 'ex-start' %}" class="glow-on-hover d-flex-col-cent">Add new exercise</a>
                        <button type="button" id="deleteExerciseBtn" class="red-glow-on-hover danger-btn">
                            Delete Selected Exercise
                        </button>
                    </div>

                </section>

                <hr class="hr-line">

                <section class="exercise-logs">
                    <h2>Conducted Exercises and Sets</h2>
                    {% if exercises %}
                        {% for exercise in exercises %}
                            <div class="exercise-log">
                                <h3>{{ exercise.name }} (Muscle Group: {{ exercise.muscle_group.name }})</h3>

                                {% if exercise.sets.all %}
                                    <ul>
                                        {% for set in exercise.sets.all %}
                                            <li>Repetitions: {{ set.repetitions }}, Weight: {{ set.weight }} kg</li>
                                        {% endfor %}
                                    </ul>
                                {% else %}
                                    <p>No sets recorded yet for this exercise.</p>
                                {% endif %}
                            </div>
                        {% endfor %}
                    {% else %}
                        <p>No exercises recorded yet.</p>
                    {% endif %}
                </section>

                <button type="submit" class="glow-on-hover">Finish Workout</button>
            </form>


        </div>
    </div>

{% endblock %}

templates/workouts/wt-type-create.html
{% extends 'base.html' %}
{% load placeholder_filter %}
{% load static %}

{% block  content %}
    <div class="background-img d-flex-col-cent">
        <div class="container blur-background">
            <form class="wt-type-form d-flex-col-cent gap25" method="post" action="{% url 'wt-type-create' %}">
                {% csrf_token %}

                <div class="input-field">
                    <h4 class="label">Workout Type Name:</h4>
                    {{ form.name|placeholder:"e.g., Full Body, Upper Body, Lower Body" }}
                    <div class="error-field fade-effect">
                        {{ form.name.errors }}
                    </div>
                </div>

                <div class="btn-container d-flex gap15">
                    <button type="submit" class="glow-on-hover">Save Workout Type</button>
                    <a href="{% url 'wt-create' %}" class="red-glow-on-hover d-flex-col-cent">Back to Workout Creation</a>
                </div>
            </form>
        </div>
    </div>
{% endblock %}