body_forge/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls')),
    path('accounts/', include('accounts.urls')),
    path('workout/', include('workouts.urls')),
    path('forum/', include('forum.urls')),
]

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forum/urls.py
from django.urls import path, include

from forum.views import CreateQuestion, ListQuestionsView, approve_question, DetailsQuestionView, delete_question, \
    AnswerCreateView

urlpatterns = [
    path('', include([
        path('', ListQuestionsView.as_view(), name='qu-list'),
        path('add-question/', CreateQuestion.as_view(), name='qu-create'),
        path('question/<int:question_pk>/add-answer/', AnswerCreateView.as_view(), name='an-create'),
        path('details-qu/<int:pk>/', DetailsQuestionView.as_view(), name='qu-details'),
        path('approve-qu/<int:pk>/', approve_question, name='qu-approve'),
        path('delete-qu/<int:pk>/', delete_question, name='qu-delete'),
    ])),
]

forum/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django_extensions.db.models import TimeStampedModel

UserModel = get_user_model()


class Question(TimeStampedModel):
    user = models.ForeignKey(
        to=UserModel,
        on_delete=models.CASCADE,
        related_name='asked_questions',
        verbose_name='Asked By',
    )
    title = models.CharField(
        max_length=200,
        verbose_name='Question Title'
    )
    content = models.TextField(
        verbose_name='Question Details'
    )
    approved = models.BooleanField(
        default=False,
    )

    class Meta:
        permissions = [
            ('approve_question', 'Can approve question'),
        ]

class Answer(TimeStampedModel):
    question = models.ForeignKey(
        'Question',
        on_delete=models.CASCADE,
        related_name='answers'
    )
    user = models.ForeignKey(
        to=UserModel,
        on_delete=models.CASCADE,
        related_name='answers',
    )
    content = models.TextField(
        verbose_name='Your Answer'
    )

    def __str__(self):
        return f'Answer by {self.user.email} on "{self.question.title}"'

forum/forms.py
from django import forms

from forum.models import Question, Answer


class QuestionBaseForm(forms.ModelForm):
    class Meta:
        model = Question
        exclude = ('user', 'approved',)


class QuestionCreateForm(QuestionBaseForm):
    pass


class AnswerCreateForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        widgets = {
            'content': forms.Textarea(attrs={'rows': 4, 'placeholder': 'Write your answer here...'}),
        }

forum/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DetailView

from forum.forms import QuestionCreateForm, AnswerCreateForm
from forum.models import Question, Answer


class ListQuestionsView(LoginRequiredMixin, ListView):
    model = Question
    template_name = 'forum/qu-list.html'

    def get_queryset(self):
        queryset = self.model.objects.all()
        if not self.request.user.has_perm('forum.approve_question'):
            queryset = queryset.filter(approved=True)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['all_questions'] = self.get_queryset()
        return context


def approve_question(request, pk):
    if request.method == 'POST':
        question = Question.objects.get(pk=pk)
        question.approved = True
        question.save()

    return redirect('qu-list')


def delete_question(request, pk):
    if request.method == 'POST':
        question = get_object_or_404(Question, pk=pk)
        question.delete()

    return redirect('qu-list')


class CreateQuestion(LoginRequiredMixin, CreateView):
    model = Question
    form_class = QuestionCreateForm
    template_name = 'forum/qu-create.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('dashboard', kwargs={'pk': self.request.user.pk})


class DetailsQuestionView(LoginRequiredMixin, DetailView):
    model = Question
    template_name = 'forum/qu-details.html'
    context_object_name = 'question'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['answers'] = self.object.answers.all()
        return context


class AnswerCreateView(LoginRequiredMixin, CreateView):
    model = Answer
    form_class = AnswerCreateForm
    template_name = 'forum/an-create.html'
    context_object_name = 'answer'

    def dispatch(self, request, *args, **kwargs):
        self.question = get_object_or_404(Question, pk=kwargs['question_pk'])
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.question = self.question
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('qu-details', kwargs={'pk': self.question.pk})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['question'] = self.question
        return context

templates/forum/an-create.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="background-img d-flex-col-cent">
        <div class="qu-container blur-background d-flex-col-cent">
            <h2 class="second-title">{{ question.title }}</h2>
            <p class="qu-content">{{ question.content }}</p>
        </div>


        <form method="post" class="qu-container blur-background d-flex-col-cent">
            {% csrf_token %}
            <div class="qu-content">
                <h4 class="label">Your Answer:</h4>
                {{ form.content }}
            </div>
            <button type="submit" class="glow-on-hover">Submit Answer</button>
        </form>

        <a href="{% url 'qu-details' pk=question.pk %}" class="red-glow-on-hover d-flex-col-cent">Back to Question</a>
    </div>
{% endblock %}

templates/forum/qu-create.html
{% extends 'base.html' %}
{% load placeholder_filter %}
{% load static %}

{% block content %}
    <div class="background-img d-flex-col-cent">
        <div class="container blur-background">
            <form class="d-flex-col-cent gap25" method="post" action="{% url 'qu-create' %}">
                {% csrf_token %}

                <div class="input-field">
                    <h4 class="label">What is your question?</h4>
                    {{ form.title|placeholder:"Enter your question title here" }}
                    <div class="error-field fade-effect">
                        {{ form.title.errors }}
                    </div>
                </div>

                <div class="input-field">
                    <h4 class="label">Provide more details:</h4>
                    {{ form.content|placeholder:"Explain your question in more detail" }}
                    <div class="error-field fade-effect">
                        {{ form.content.errors }}
                    </div>
                </div>

                {{ form.non_field_errors }}

                <button type="submit" class="glow-on-hover">Post Your Question</button>
            </form>
        </div>
    </div>
{% endblock %}

templates/forum/qu-details.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="background-img d-flex-col-cent">
        <label class="second-title" for="qu-content">{{ question.title }}</label>
        <div class="qu-container blur-background d-flex-sp-between">
            <p>Question:</p>
            <p class="qu-content" id="qu-content">{{ question.content }}</p>
        </div>

        {% if perms.forum.approve_question and not question.approved %}
            <div class="btn-container">
                <form method="post" action="{% url 'qu-approve' question.pk %}" style="display:inline;">
                    {% csrf_token %}
                    <button type="submit" class="glow-on-hover">Approve Question</button>
                </form>

                <form method="post" action="{% url 'qu-delete' question.pk %}" style="display:inline;">
                    {% csrf_token %}
                    <button type="submit" class="red-glow-on-hover">Delete Question</button>
                </form>
            </div>
        {% endif %}

        {% for answer in answers %}
            <div class="qu-container blur-background d-flex-sp-between">
                <label class="second-title" for="qu-content">Answered by: {{ answer.user.profile.username }}</label>
                <p class="qu-content" id="qu-content">{{ answer.content }}</p>
            </div>
            <p style="color: var(--smoke-white)">{{ answer.created }}</p>
        {% empty %}
            <p>No answers yet.</p>
        {% endfor %}

        <div class="btn-container d-flex gap25">
            {% if user.is_authenticated and user != question.user and perms.forum.add_answer %}
                <a class="glow-on-hover d-flex-col-cent" href="{% url 'an-create' question_pk=question.pk %}">Post Your Answer</a>
            {% endif %}
            <a href="{% url 'qu-list' %}" class="red-glow-on-hover d-flex-col-cent">Back to Forum</a>
        </div>
    </div>


{% endblock %}

templates/forum/qu-list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="background-img d-flex-col-cent">
        <div class="content-stack-grow">
            <ul class="qu-container">
                {% for qu in all_questions %}

                    <li>
                        <a href="{% url 'qu-details' qu.pk %}">
                            <div class="blur-background question-li">
                                <p><strong>Question by:</strong> {{ qu.user.profile.username }}</p>
                                <p><strong>Title:</strong> {{ qu.title }}</p>
                                <p><strong>Posted on:</strong> {{ qu.created }}</p>

                                {% if perms.forum.approve_question %}
                                    {% if qu.approved %}
                                        <p style="color: green;">Status: Approved</p>
                                    {% else %}
                                        <p style="color: red;">Status: Pending Approval</p>
                                    {% endif %}
                                {% endif %}
                            </div>
                        </a>
                    </li>

                {% empty %}
                    <h2>The forum is quiet right now.</h2>
                    <p>Be the first to ask a question and get the conversation started!</p>
                    <a href="{% url 'qu-create' %}" class="glow-on-hover d-flex-col-cent">Ask a Question</a>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}